[project]
name = "dmd_thesis"
version = "0.1"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "matplotlib>=3.10.1",
    "scipy>=1.15.2",
    "pydmd>=2025.4.1",
    "pytest",
    "pyqt5",
]
